// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://imzwknqvxqfqldnczpdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltendrbnF2eHFmcWxkbmN6cGR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MjY2NzIsImV4cCI6MjA3NjIwMjY3Mn0.-Cil580owgjhMJ08EZxiJYIpbcjzRu3XEgWhOal7VL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);